mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="tasks/password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="tasks/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="tasks/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="tasks/password_reset_done.html"), 
        name="password_reset_complete"),
]

'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password reset form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

tasks/urls.py
from django.urls import path



from . import views

app_name = 'tasks'
urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),  
    path('logout/', views.logoutUser, name="logout"),

    path('', views.index, name="index"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('update/<str:pk>/', views.update, name="update"),
    path('delete/<int:pk>/', views.delete, name="delete"),
    path('share/<int:pk>/', views.share, name="share"),
]

tasks/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
from django.contrib.auth.models import User

class Task(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    readers = models.ManyToManyField(User, related_name='permitted_tasks', through='TaskPermission', blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    expiration_date = models.DateTimeField(null=True)

    @property
    def expired(self):
        if self.expiration_date is not None and timezone.now() > self.expiration_date:
            return True
        return False

    @property
    def finishes_in_10_minutes(self):

        now = timezone.now()
        dt = self.expiration_date.replace(second=0, microsecond=0) - now.replace(second=0, microsecond=0)
        if dt == datetime.timedelta(minutes=10):
            return True
        return False
    

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.body


class TaskPermission(models.Model):
    reader = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    comment = models.BooleanField(default=False)

tasks/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

from django.utils import timezone

from .models import *

class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            # Add bootstrap class for visible fields
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Task
        fields = ['title', 'description', 'expiration_date']
        widgets = {
            'expiration_date': forms.DateTimeInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }
        help_texts = {
            'expiration_date': 'YYYY-MM-DD HH:MM:SS',
        }

    def clean_expiration_date(self):
        picked_date = self.cleaned_data['expiration_date']
        if picked_date:
            if timezone.now() > picked_date:
                # Impossible date seleceted
                raise forms.ValidationError('Choose time in the future')

        return picked_date



class  ShareForm(forms.Form):            
    username = forms.CharField(max_length=30, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    comment = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    def clean(self):
        #super().clean() - deqiqleshdir
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if username:
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                raise forms.ValidationError('User with such username does not exist')
        elif email:
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                raise forms.ValidationError('User with such email does not exist')
        else:
            raise forms.ValidationError('Provide username or email')

        self.user = user
        return self.cleaned_data

    @property
    def user_to_share(self):
        return getattr(self, 'user')


class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            # Add bootstrap class for visible fields
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
	    model = User
	    fields = ['username', 'email', 'password1', 'password2']

tasks/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
import pytz

from django.utils.safestring import mark_safe
import json
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required


from .permissions import *

from .decorators import *

@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            messages.success(request, 'Account was created for ' + username)

            return redirect('tasks:login')

    context = {'form':form}
    return render(request, 'tasks/register.html', context)


@unauthenticated_user
def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username OR password is incorrect')


    context = {}
    return render(request, 'tasks/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('tasks:login')

#from .tasks import send_email_task
# Create your views here.
@login_required(login_url='tasks:login')
def index(request):
    user = request.user
    user_tasks = Task.objects.filter(author=user)
    permitted_tasks = get_permitted_tasks(user)
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = user
            task.save()
            return redirect('/')

    context = {'form':form,'user_tasks':user_tasks,'permitted_tasks':permitted_tasks}
    return render(request, 'tasks/index.html', context)


@login_required(login_url='tasks:login')
@author_or_reader
def detail(request, pk):
    task = Task.objects.get(id=pk)

    comments = task.comments.all()
    context = {'task':task,'comments':comments}
    return render(request, 'tasks/detail.html', context)


@login_required(login_url='tasks:login')
@author
def update(request, pk):
    task = Task.objects.get(id=pk)

    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        
        if form.is_valid():
            form.save()
            return redirect('/')
           

    context ={'form': form}

    return render(request, 'tasks/update.html', context)


@login_required(login_url='tasks:login')
@author
def delete(request, pk):
    task = Task.objects.get(id=pk)

    if request.method == 'POST':
	    task.delete()
	
    return redirect('/')


@login_required(login_url='tasks:login')
@author
def share(request, pk):
    form = ShareForm()
    task = Task.objects.get(id=pk)
   
    if request.method == 'POST':
        form = ShareForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data.get('comment')
            user = form.user_to_share
            assign_task_permission(user, task, comment)

            return redirect('/')

    context ={'form':form}

    return render(request, 'tasks/share.html', context)

tasks/templates/tasks/detail.html
{% extends 'tasks/index.html' %}
{% load static %}
{% load permission_extras %}


{% block content %}
<div class="center-column">
    <h4>{{task.title}}</h4>
    <p>{{task.description}} on <time>{{task.expiration_date}}</time></p>
    <p> {{task.author}}</p>
</div>

<div class="center-column">
    <h4>Comments:</h4>
    <div id="comments-container">
        {% for comment in comments %}
            <div data-id="{{comment.id}}" class="card bg-light mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{comment.author.username}}</h5>
                    <p class="card-text">{{comment.body}}</p>
                    {% if user|can_edit_comment:comment %}
                    <input onclick="editComment(event)" data-id="{{comment.id}}" type="button" class="btn btn-success btn-sm edit-comment" value="Edit">
                    {% endif %}
                    {% can_delete_comment user comment task as can_delete_tag %}
                    {% if can_delete_tag %}
                    <input onclick="deleteComment(event)"  data-id="{{comment.id}}" type="button" class="btn btn-danger btn-sm delete-comment" value="Delete">
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% if user|can_comment:task %}
<div class="center-column">
    <textarea class="form-control mb-0" id="comment-input" placeholder="Write a comment..."></textarea><br>
    <input type="button" class="btn btn-primary mt-0 main" id="comment-submit" value="Send">
</div>
{% endif %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js'></script>
<script>
    
/*  
    //console.log(window.location) 
    Brad version
    var loc = window.location
    var wsStart = 'ws://'
    if(loc.protocol == 'https:'){
        wsStart = 'wss://' 
    }
    var endpoint = wsStart + loc.host + loc.pathname
    var commentSocket = new ReconnectingWebSocket(endpoint);
*/

    var task_id = '{{task.id}}';

    var loc = window.location
    var wsStart = 'ws://'
    if(loc.protocol == 'https:'){
        wsStart = 'wss://'  //for production
    }
    var commentSocket = new ReconnectingWebSocket(wsStart + window.location.host + '/ws/comment/' + task_id + '/');


    //function to set a focus cursor to the end of the text, while editting comment
    // Credits: http://blog.vishalon.net/index.php/javascript-getting-and-setting-caret-position-in-textarea/
    function setCaretPosition(ctrl, pos) {
    // Modern browsers
        if (ctrl.setSelectionRange) {
            ctrl.focus();
            ctrl.setSelectionRange(pos, pos);
        
        // IE8 and below
        } else if (ctrl.createTextRange) {
            var range = ctrl.createTextRange();
            range.collapse(true);
            range.moveEnd('character', pos);
            range.moveStart('character', pos);
            range.select();
        }
    }

    commentSocket.onmessage = function(e){

        const data = JSON.parse(e.data);
        if(data.operation == "create") {
            
            var card = document.createElement("div");
            card.setAttribute('data-id', data.commentId)
            card.classList.add("card", "bg-light", "mb-3");
            
            createCardBody();

            var commentsContainer = document.getElementById("comments-container");
            commentsContainer.append(card);
        }

        if(data.operation == "delete"){
            var dataId = data.commentId
            
            var card = document.querySelector(`.card[data-id="${dataId}"]`)
            
            card.parentNode.removeChild(card);

        }
        if(data.operation == "edit"){
           
            var dataId = data.commentId
           
            
            var card = document.querySelector(`.card[data-id="${dataId}"]`)

            card.innerHTML = ''
            
            createCardBody();

        }

        //to avoid redundancy in create and edit 
        function createCardBody(){
            var cardBody = document.createElement("div");
            cardBody.classList.add("card-body");
            
            var cardTitle = document.createElement("h5");
            cardTitle.classList.add("card-title");
            cardTitle.innerHTML = data.username

            var cardText = document.createElement("p");
            cardText.classList.add("card-text");
            cardText.innerHTML = data.message;

            card.appendChild(cardBody);

            cardBody.appendChild(cardTitle);
            cardBody.appendChild(cardText);
            
            if(data.username == user){
            // Append Edit Button
            var editButton = document.createElement('input')
            editButton.setAttribute('onclick', 'editComment(event)')
            editButton.setAttribute('data-id', data.commentId)
            editButton.setAttribute('type', 'button')
 
            editButton.className = 'btn btn-success btn-sm edit-comment'
            editButton.setAttribute('value', 'Edit')
            cardBody.appendChild(editButton)
            }
            
            if(data.username == user || data.taskAuthor == user){
            // Append Delete Button
            var deleteButton = document.createElement('input')
            deleteButton.setAttribute('onclick', 'deleteComment(event)')
            deleteButton.setAttribute('data-id', data.commentId)

            deleteButton.setAttribute('type', 'button')

            deleteButton.className = 'btn btn-danger btn-sm delete-comment'
            deleteButton.setAttribute('style', 'margin-left:0.25rem')
            deleteButton.setAttribute('value','Delete')
            cardBody.appendChild(deleteButton)
            }

        }
    }

    commentSocket.onopen = function(e){
        console.log("open",e)
    }

    commentSocket.onerror = function(e){
        console.log("error",e)
    }

    commentSocket.onclose = function(e){
         console.error('Comment socket closed unexpectedly');
    }
    
    document.querySelector('#comment-input').focus();
    document.querySelector('#comment-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#comment-submit').click();
        }
    };

    document.querySelector('#comment-submit').onclick = function(e) {

        const messageInputDom = document.querySelector('#comment-input');
        const message = messageInputDom.value;
        commentSocket.send(JSON.stringify({
            'message': message,
            'taskId': {{task.id}},
            'operation': "create"
        }));
        messageInputDom.value = '';
    };


    function deleteComment(e){
        commentId = parseInt(e.target.getAttribute('data-id'));

        commentSocket.send(JSON.stringify({
            'taskId': {{task.id}},
            'commentId': commentId,
            'operation': "delete"
        }));            
    }


    function editComment(e){
   
        dataId = parseInt(e.target.getAttribute('data-id'));
        var card = document.querySelector(`.card[data-id="${dataId}"]`)

        var cardBody = card.querySelector('.card-body')
        comment_text = cardBody.querySelector('.card-text').innerText
        cardBody.hidden = true;


        var commentTextarea = document.createElement('div')
        commentTextarea.className = 'card-body comment-textarea'


        var editionTextarea = document.createElement('textarea')
        editionTextarea.className = 'form-control'

        editionTextarea.innerText = comment_text
        commentTextarea.appendChild(editionTextarea)

        

        saveButton = document.createElement('input')
        saveButton.setAttribute('type', 'button')
        saveButton.setAttribute('value', 'Save')
        saveButton.className = 'btn btn-primary btn-sm m-1'
        commentTextarea.appendChild(saveButton)

        
        cancelButton = document.createElement('input')
        cancelButton.setAttribute('type', 'button')
        cancelButton.setAttribute('value', 'Cancel')
        cancelButton.className = 'btn btn-secondary btn-sm m-1'
        commentTextarea.appendChild(cancelButton)

        card.appendChild(commentTextarea)

        //start cursor from the end of the text line
        editionTextarea.onfocus = function() {
            setCaretPosition(editionTextarea, editionTextarea.value.length);
        }
        editionTextarea.focus()

        // if cancel edition
        cancelButton.onclick = function(){
             cancelEdit(cardBody, commentTextarea)
        }

        //use enter to submit
        editionTextarea.onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
               saveButton.click();
            }
        };
        
        // i won't treat the case when there is no changes, cuz i'm lazy and it's 3 am now - so it'll update anyway
        saveButton.onclick = function(){
            message = editionTextarea.value
     
            commentSocket.send(JSON.stringify({
            'taskId': {{task.id}},
            'commentId': dataId,
            'message': message,
            'operation': "edit"
            }));    
        };
    }


    function cancelEdit(cardBody, commentTextarea){
        commentTextarea.parentNode.removeChild(commentTextarea)
        cardBody.hidden = false
    }

</script>
{% endblock %}

tasks/templates/tasks/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script>
        var user = '{{request.user}}'
    </script>
</head>
<body>
	{%  include 'tasks/navbar.html' %}
	
    {% block content %}
    <div class="center-column">
        {% if user_tasks %}
        <div class="item-row" id="tasks-header">
            <h4>Your Tasks:</h4>
        </div>
        {% endif %}
        {% for task in user_tasks %}
        <div class="item-row">
                <div class="d-flex justify-content-between mb-3">
                    <a class="link-light p-2" href="{% url 'tasks:detail' task.id %}"><h3>{{task.title}}</h3></a>
                    <a type="button" class="btn btn-outline-light p-2" href="{% url 'tasks:share' task.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-reply" viewBox="0 0 16 16">
                            <path d="M6.598 5.013a.144.144 0 0 1 .202.134V6.3a.5.5 0 0 0 .5.5c.667 0 2.013.005 3.3.822.984.624 1.99 1.76 2.595 3.876-1.02-.983-2.185-1.516-3.205-1.799a8.74 8.74 0 0 0-1.921-.306 7.404 7.404 0 0 0-.798.008h-.013l-.005.001h-.001L7.3 9.9l-.05-.498a.5.5 0 0 0-.45.498v1.153c0 .108-.11.176-.202.134L2.614 8.254a.503.503 0 0 0-.042-.028.147.147 0 0 1 0-.252.499.499 0 0 0 .042-.028l3.984-2.933zM7.8 10.386c.068 0 .143.003.223.006.434.02 1.034.086 1.7.271 1.326.368 2.896 1.202 3.94 3.08a.5.5 0 0 0 .933-.305c-.464-3.71-1.886-5.662-3.46-6.66-1.245-.79-2.527-.942-3.336-.971v-.66a1.144 1.144 0 0 0-1.767-.96l-3.994 2.94a1.147 1.147 0 0 0 0 1.946l3.994 2.94a1.144 1.144 0 0 0 1.767-.96v-.667z"></path>
                        </svg>
                        Share
                    </a>
                </div>
                <p>{{task.description}}</p>
                {% if task.expiration_date and not task.expired %}
                <p>Deadline:  <time>{{task.expiration_date}}</time></p>
                {% endif %}
                {% if task.expired %}
                <p>Deadline:  <b style="color: red;">Expired</b></p>
                {% endif %}
                <p> {{task.author}}</p>
                <form method="POST" action="{% url 'tasks:delete' task.id %}">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger delete" name="delete" value="Delete" >
                </form>
                <a class="btn btn-success" href="{% url 'tasks:update' task.id %}">Update Task</a>
        </div>
        {% endfor %}
        {% if permitted_tasks %}
        <div class="item-row" id="tasks-header">
            <h4>Tasks shared with you:</h4>
        </div>
        {% endif %}
        {% for task in permitted_tasks %}
        <div class="item-row">
                <a class="link-light p-2" href="{% url 'tasks:detail' task.id %}"><h3>{{task.title}}</h3></a>
                <p>{{task.description}}</p>
                {% if task.expiration_date and not task.expired %}
                <p>Deadline:  <time>{{task.expiration_date}}</time></p>
                {% endif %}
                {% if task.expired %}
                <p>Deadline:  <b style="color: red;">Expired</b></p>
                {% endif %}
                <p> {{task.author}}</p>
        </div>
        {% endfor %}

   
        <div class="container-sm">
            <form method="POST" action="/">
            {% csrf_token %}
                <div class="row g-2">
                    {{form}}
                </div>
                <input class="btn btn-info main" type="submit" name="Create Task">
            </form>
        </div>
    </div>

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

tasks/templates/tasks/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'tasks:register' %}" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						Forgot password? <a href="{% url 'reset_password' %}" class="ml-2">Reset password</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

tasks/templates/tasks/navbar.html
{% load static %}


<style>
  .hello-msg{
    font-size: 18px;
    color: #6e08eb;
    margin-right: 20px;
  }
  .nav-link{
    color: #6e08eb !important;
  }

</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light"> 
<a href="{% url 'tasks:index' %}"><img src="{% static 'images/logo.png' %}" width="120" class="logo"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'tasks:index' %}">Tasks</a>
      </li>

    </ul>
  </div>

  <span class="hello-msg">Hello, {{request.user}}</span> 
  <span><a class="hello-msg" href="{% url 'tasks:logout' %}">Logout</a></span>

</nav>

tasks/templates/tasks/password_reset.html
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>

tasks/templates/tasks/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="/">Log in</a>

tasks/templates/tasks/password_reset_form.html
<h3>Enter new password</h3>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">
	
</form>

tasks/templates/tasks/password_reset_sent.html
<h3>Password reset sent</h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

tasks/templates/tasks/share.html
{% extends 'tasks/index.html' %}
{% load static %}
{% block content %}
<div class="center-column">

    <form method="POST" action="">
        {% csrf_token %}
        <div class="row g-2">
            {{form}}
        </div>
        <input class="btn btn-info main" type="submit" name="shareTask" value="Share Task">
    </form>
</div>
{% endblock %}

tasks/templates/tasks/update.html
{% extends 'tasks/index.html' %}
{% load static %}
{% block content %}
<div class="center-column">

    <form method="POST" action="">
        {% csrf_token %}
        <div class="row g-2">
            {{form}}
        </div>
        <input class="btn btn-success main" type="submit" name="updateTask" value="Update Task">
    </form>
</div>
{% endblock %}